theme: just-the-docs
url: https://river-lab.github.io/prospect/
title: PROSPECT

callouts_level: loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

aux_links:
  "PROSPECT on GitHub":
    - "https://github.com/RIVeR-Lab/prospect/tree/main"

nav_external_links:
  - title: PROSPECT on GitHub
    url: https://github.com/RIVeR-Lab/prospect/tree/main

back_to_top: true
back_to_top_text: "Back to top"